### PR TITLE
1.19.2 Backport

### PR DESCRIPTION
**Pull request by SiverDX**
Tested on Forge and Fabric

### CODE REVIEW

**Comment by AlexNijjar** [comment]
what is the purpose of this? there is already a 1.19.2 version

**Comment by SiverDX** [comment]
But not with the latest changes which were only for 1.19.2

**Comment by AlexNijjar** [comment]
I'm very confused. The only difference between the 1.19.2 version and the current 1.19.4 version is an optimization to the recipes. Everything else is functionally identical. So is this PR meant to backport that specific change?

**Comment by SiverDX** [comment]
yes + the part where you switched to json config for the features (meaning you can customize them with a datapack)

**Pull request closed without merging**
